application: supermeeple-sk
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on

handlers:
- url: /static
  static_dir: static
  
- url: /js
  static_dir: javascript
  
- url: /.*
  script: main.py  