application: supermeeple-sk
version: 1
#version: staging
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: on

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /js
  static_dir: javascript

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin  

- url: /api/.*
  script: api.py
  
- url: /.*
  script: main.py  
 
  


  