application: supermeeple-sk
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- appstats: off

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /js
  static_dir: javascript

- url: /_ah/queue/.*
  script: meeple_tasks.py
  login: admin
  
- url: /.*
  script: main.py  

error_handlers:
  - file: templates/base_404.html

  